import Head from 'next/head'

import axios from 'axios'

import { useState, useEffect } from 'react'

import { Row, Col, List, Breadcrumb} from 'antd'
import {CalendarOutlined, FolderOutlined, FireOutlined } from '@ant-design/icons'

import homesty from '../styles/pages/Home.module.css'
import listy from '../styles/pages/list.module.css'
import service_path from '../config/apiurl.js'

import Header from '../components/Header'
import Author from '../components/Author'
import Card from '../components/Card'

function Mylist(props) {
  
/*   const [navArray , setNavArray] = useState([])
  useEffect(()=>{

      const fetchData = async ()=>{
         const result= await axios(service_path.getypeinfo).then(
              (res)=>{
                  return res.data.data
              }
            )
         setNavArray(result) //获得type赋值给navArray
      }
      fetchData()
  },[]) */

  return (
    <div className={homesty.container}>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className={homesty.commain} type="flex" justify="center">
        <Col className={homesty.commleft} xs={24} sm={24} md={16} lg={18} xl={14}>
          <div className = {listy.bread_div}>
            <Breadcrumb>
                <Breadcrumb.Item><a href = "/"> 首页</a> </Breadcrumb.Item>
                <Breadcrumb.Item> 所有笔记 </Breadcrumb.Item>
            </Breadcrumb>
          </div>
          <List 
            header={<div> 最新笔记 </div>} 
            itemLayout = "vertical"
            dataSource = {props.data}
            renderItem = {(item)=>{
              return (
                <List.Item>
                  <div className = {listy.list_title}>{item.title}</div>
                  <div className = {listy.list_icon}>
                  <span><CalendarOutlined/>2021-1-1</span>
                  <span><FolderOutlined/>笔记</span>
                  <span><FireOutlined/>000</span>
                  </div>
                  <div className = {listy.list_context}>{item.context}</div>
                 
                </List.Item>
              )}}
              
          />
        </Col>
        <Col className={homesty.commright} xs={0} sm={0} md={7} lg={5} xl={4}>
         <Author />
         <Card />
        </Col>
      </Row>


      <footer className={homesty.footer}>
        <div>Powered by React + Node + Ant Desgin </div>
      </footer>
    </div>
  )
}

Mylist.getInitialProps = async ()=>{ //接收初始值，也就是形参list
  const promise = new Promise((resolve)=>{
    axios(service_path.urlarticlelist).then(
      (res)=>{
        //console.log('=======>',res)
        resolve(res.data);
      }
    )
  })
  return await promise;
}


export default Mylist;